# Generated by Django 5.1 on 2024-08-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0002_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.TextField(max_length=4, null=True),
        ),
    ]
